### ISSUE TITLE
DFD Comments - Sept 14

### ISSUE THREAD

**Issue by germonprez** [drschriner/Assignment-1-ISQA-3420#12]
Your datastore should be: OSS Software and License Information

Outside of that, things look good.

**Comment by drschriner** [comment]
Update DFD image after review. 
![dfd 9 14](https://cloud.githubusercontent.com/assets/21317639/18532641/feabcdf0-7aa2-11e6-99c7-bb21b698d3ec.PNG)

**Comment by drschriner** [comment]
Done!
